# Generated by Django 2.0.7 on 2018-07-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='colours.Palette'),
        ),
    ]
