# Generated by Django 2.0.7 on 2018-07-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colours', '0002_auto_20180711_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='hex_code',
            field=models.CharField(max_length=7, unique=True, verbose_name='hexidecimal code'),
        ),
    ]
